### ISSUE TITLE
GET /pilots/:id is broken (500 internal error)

### ISSUE THREAD

**Issue by djmolny** [wbreeze/iaccdb#142] opened 2019-10-02 23:49 UTC
Example: https://iaccdb.iac.org/pilots/664

From the log file:
`F, [2019-10-02T18:47:27.070365 #25597] FATAL -- : [6e8d55dd-4ff3-4464-a7ae-ae75f6fb9397] ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'f.category_id' in 'where clause': select distinct
      c.id, c.name, c.start, c.region, t.name as category
      from pilot_flights p, members m, flights f, contests c, categories t
      where p.pilot_id = '664' and p.flight_id = f.id and f.contest_id = c.id
      and t.id = f.category_id
      order by c.start desc):
`

**Comment by wbreeze** [comment] 2019-10-03 14:51
Duplicate of #134

**Closed by wbreeze** 2019-10-03 14:51 UTC
